name: flowly
description: FlowLy — a next-generation music app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.0.1
  line_icons: ^2.0.1
  assets_audio_player: ^3.0.5
  provider: ^6.0.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/Proxima-Nova-SBold.ttf
    - family: Proxima Bold
      fonts:
        - asset: fonts/Proxima-Nova-Bold.ttf
