name: flowly
description: FlowLy — a next-generation music app.
publish_to: "none"
version: 1.0.11+12

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.5.0
  cached_network_image: ^3.3.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  collection: ^1.19.1
  line_icons: ^2.0.3
  just_audio: ^0.10.6
  just_audio_background: ^0.0.1-beta.17
  sqflite: ^2.4.3
  provider: ^6.1.5+1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/Proxima-Nova-Sbold.ttf
    - family: Proxima Bold
      fonts:
        - asset: fonts/Proxima-Nova-Bold.ttf
