import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flowly/core/storage/settings_service.dart';
import 'package:flowly/app/localization/app_locale.dart';

class PlaybackSettingsPage extends StatefulWidget { const PlaybackSettingsPage({super.key}); @override State<PlaybackSettingsPage> createState()=>_PlaybackSettingsPageState(); }
class _PlaybackSettingsPageState extends State<PlaybackSettingsPage>{ late bool autoplay,gapless,normalize; late String repeat,quality; late double crossfade; Box<dynamic> get box=>Hive.box('profile'); @override void initState(){super.initState();autoplay=box.get('playbackAutoplay',defaultValue:true) as bool;gapless=box.get('playbackGapless',defaultValue:true) as bool;normalize=box.get('playbackNormalize',defaultValue:false) as bool;repeat=box.get('playbackRepeat',defaultValue:'off') as String;quality=box.get('playbackQuality',defaultValue:'standard') as String;crossfade=(box.get('playbackCrossfade',defaultValue:0.0) as num).toDouble();} Future<void> put(String key,Object value,VoidCallback update)async{await box.put(key,value);if(mounted)setState(update);} @override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,foregroundColor:Colors.white,title:Text(AppLocale.text('Воспроизведение','Playback'))),body:ListView(padding:const EdgeInsets.all(20),children:[_Toggle('Автовоспроизведение','Autoplay',autoplay,(v)=>put('playbackAutoplay',v,()=>autoplay=v)),_Toggle('Без пауз','Gapless playback',gapless,(v)=>put('playbackGapless',v,()=>gapless=v)),_Toggle('Нормализация громкости','Volume normalization',normalize,(v)=>put('playbackNormalize',v,()=>normalize=v)),_Choice('Повтор','Repeat',repeat,const {'off':'Выключен','all':'Очередь','one':'Трек'},(v)=>put('playbackRepeat',v,()=>repeat=v)),_Choice('Качество','Quality',quality,const {'standard':'Стандарт','high':'Высокое','maximum':'Максимальное'},(v)=>put('playbackQuality',v,()=>quality=v)),_SliderCard(title:AppLocale.text('Crossfade','Crossfade'),value:crossfade,onChanged:(v)=>put('playbackCrossfade',v,()=>crossfade=v)),_Info(AppLocale.text('Статус','Status'),AppLocale.text('Параметры сохраняются сразу. Реальный Crossfade/EQ и серверное качество будут подключены к audio/backend pipeline отдельно.','Settings are persisted immediately. Real Crossfade/EQ and server-side quality will be connected to the audio/backend pipeline separately.'))])); }

class NotificationSettingsPage extends StatefulWidget{const NotificationSettingsPage({super.key});@override State<NotificationSettingsPage> createState()=>_NotificationSettingsPageState();}
class _NotificationSettingsPageState extends State<NotificationSettingsPage>{late bool music,downloads,updates;Box<dynamic> get box=>Hive.box('profile');@override void initState(){super.initState();music=box.get('notifyMusic',defaultValue:true) as bool;downloads=box.get('notifyDownloads',defaultValue:true) as bool;updates=box.get('notifyUpdates',defaultValue:true) as bool;}Future<void> toggle(String key,bool value,VoidCallback update)async{await box.put(key,value);if(mounted)setState(update);}@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,foregroundColor:Colors.white,title:Text(AppLocale.text('Уведомления','Notifications'))),body:ListView(padding:const EdgeInsets.all(20),children:[_Toggle('Музыка','Music',music,(v)=>toggle('notifyMusic',v,()=>music=v)),_Toggle('Загрузки','Downloads',downloads,(v)=>toggle('notifyDownloads',v,()=>downloads=v)),_Toggle('Обновления','Updates',updates,(v)=>toggle('notifyUpdates',v,()=>updates=v)),_Info(AppLocale.text('Плеер','Player'),AppLocale.text('Android Media notification получает название, исполнителя и обложку из MediaItem. Play/Pause/Previous/Next управляются системным аудиоплеером.','Android Media notification receives title, artist and artwork from MediaItem. Play/Pause/Previous/Next are controlled by the system media player.'))]));}

class QuickActionsSettingsPage extends StatefulWidget{const QuickActionsSettingsPage({super.key});@override State<QuickActionsSettingsPage> createState()=>_QuickActionsSettingsPageState();}
class _QuickActionsSettingsPageState extends State<QuickActionsSettingsPage>{Box<dynamic> get box=>Hive.box('profile');late bool playerSwipe,navigationSwipe,haptics;@override void initState(){super.initState();playerSwipe=box.get('quickPlayerSwipe',defaultValue:true) as bool;navigationSwipe=SettingsService.swipeNavigationEnabled;haptics=box.get('quickHaptics',defaultValue:true) as bool;}Future<void> setValue(String key,bool value,VoidCallback update)async{await box.put(key,value);if(mounted)setState(update);}Future<void> setNavigationSwipe(bool value)async{await SettingsService.setSwipeNavigationEnabled(value);if(mounted)setState(()=>navigationSwipe=value);}@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,foregroundColor:Colors.white,title:Text(AppLocale.text('Быстрые действия','Quick actions'))),body:ListView(padding:const EdgeInsets.all(20),children:[_Toggle('Свайп в плеере','Player swipe',playerSwipe,(v)=>setValue('quickPlayerSwipe',v,()=>playerSwipe=v)),_Toggle('Свайп по разделам','Navigation swipe',navigationSwipe,setNavigationSwipe),_Toggle('Вибрация','Haptic feedback',haptics,(v)=>setValue('quickHaptics',v,()=>haptics=v)),_Info(AppLocale.text('Жесты плеера','Player gestures'),AppLocale.text('Вправо/влево переключает предыдущий/следующий трек. Настройка сохраняется локально и готова для gesture-driven контроллера.','Left/right switches previous/next. The preference is persisted and ready for the gesture-driven controller.')),_Info(AppLocale.text('Навигация','Navigation'),AppLocale.text('В разделах Главная, Поиск, Библиотека и Профиль свайп влево/вправо меняет активный раздел. Переключатель выше полностью отключает это поведение.','On Home, Search, Library and Profile, horizontal swipes change the active section. The switch above completely disables this behavior.'))]));}

class SupportSettingsPage extends StatelessWidget{const SupportSettingsPage({super.key});@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,foregroundColor:Colors.white,title:Text(AppLocale.text('Поддержка','Support'))),body:ListView(padding:const EdgeInsets.all(20),children:[_Info('FAQ',AppLocale.text('Ответы на частые вопросы будут расширяться по мере подготовки backend.','Frequently asked questions will expand as the backend is prepared.')),_Info(AppLocale.text('Сообщить об ошибке','Report a bug'),AppLocale.text('Crash reporting подключён отдельно; перед релизом проверяйте Sentry DSN в CI secrets.','Crash reporting is connected separately; before release verify the Sentry DSN in CI secrets.')),_Info(AppLocale.text('Обратная связь','Feedback'),AppLocale.text('Серверная форма обратной связи будет подключена через FlowLy-API после готовности production endpoint.','The server feedback form will be connected through FlowLy-API when the production endpoint is ready.'))]));}

class _DownloadFolderPage extends StatefulWidget{const _DownloadFolderPage();@override State<_DownloadFolderPage> createState()=>_DownloadFolderPageState();}
class _DownloadFolderPageState extends State<_DownloadFolderPage>{String? path;Box<dynamic> get box=>Hive.box('profile');@override void initState(){super.initState();path=box.get('downloadDirectory') as String?;}Future<void> pick()async{final selected=await FilePicker.getDirectoryPath(dialogTitle:AppLocale.text('Выберите папку для загрузок','Choose download folder'));if(selected==null||selected.isEmpty)return;await box.put('downloadDirectory',selected);if(mounted)setState(()=>path=selected);}Future<void> clear()async{await box.delete('downloadDirectory');if(mounted)setState(()=>path=null);}@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,foregroundColor:Colors.white,title:Text(AppLocale.text('Папка загрузок','Download folder'))),body:ListView(padding:const EdgeInsets.all(20),children:[_Info(AppLocale.text('Текущая папка','Current folder'),path??AppLocale.text('Память приложения по умолчанию','App storage by default')),FilledButton.icon(onPressed:pick,icon:const Icon(Icons.folder_open),label:Text(AppLocale.text('Выбрать папку','Choose folder')),style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:Colors.black)),if(path!=null)OutlinedButton.icon(onPressed:clear,icon:const Icon(Icons.restore),label:Text(AppLocale.text('Вернуть по умолчанию','Use default folder')),style:OutlinedButton.styleFrom(foregroundColor:Colors.white)),_Info(AppLocale.text('Скачивание','Downloads'),AppLocale.text('Реальная загрузка намеренно отключена до появления серверного API. Выбранная папка уже сохраняется и будет использована download service после подключения endpoint.','Actual downloading remains disabled until the server API is available. The selected folder is persisted and will be used by the download service once the endpoint is connected.'))]));}
